### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fluix-dev** [dbuxy218/Prismatic-Night#2]
Hey, I'd love to build upon this theme with some of my own styling, and I'd like to know whether you're okay with this. Perhaps you could also add a `LICENSE` file to this repository so others don't have to ask?

Doesn't have to be permissive or anything (as nice as that would be :p), just something that others can read.

**Comment by 3r3bu5x9** [comment]
done (and sorry for the late response)

**Comment by fluix-dev** [comment]
No problem, thanks so much for your beautiful work! Just so I don't bug you again, could you do the same for [PixelFox](https://github.com/dbuxy218/PixelFox)?

**Comment by 3r3bu5x9** [comment]
done(also thnx)
