### ISSUE TITLE
userChrome.js doesn't work

### ISSUE THREAD

**Issue by AlanTheKnight** [dbuxy218/Prismatic-Night#3]
Hello, sir. I've downloaded your theme for filefox but userChrome.js is not working. As I understand, there are some problems with firefox version. I've changed legacyUserProfileCustomizations to true, still doesn't work yet. index.html is not showing. All other files like userChrome.css work.
P.S. I have firefox 77 version.

**Comment by 3r3bu5x9** [comment]
Made major changes and tested with firefox 77. Everything is working now.
(Previously i was using firefox-esr which is version 68.9)
I have written detailed instructions. The userChrome.js is irrelevant now. There's a different method for setting the startpage as the New tab page. See the README file.
Close the thread if there isn't any more problems.
(And sorry for the late response).

**Comment by AlanTheKnight** [comment]
Thanks a lot, sir! Finally, it worked. I'm closing the issue now.
