### ISSUE TITLE
Can not make startuppage as new tab page

### ISSUE THREAD

**Issue by lakkiy** [dbuxy218/Prismatic-Night#4]
OS: Manjaro

Don't have  ```/usr/lib/firefox/defaults/pref/``` folder.

I create it and copy ```local-settings.js``` to this two place but it still don't work.

Here is the tree of ```/usr/lib/firefox```.

```
├── browser
│   └── defaults
│       └── preferences
│           ├── all-companyname.js
│           └── local-settings.js
├── defaults
│   └── pref
│       └── local-settings.js
├── distribution
└── mozilla.cfg
```

**Comment by 3r3bu5x9** [comment]
1. what is the version of Firefox?
2. have u tried reinstalling Firefox?

Delete the defaults/pref folder and see if it's auto generated after reinstallation. There should be another auto-generated file called channel-prefs.js

~~if everything fails, then make a file called channel-prefs.js and put it in defaults/pref and add the following line there: `pref("app.update.channel", "release");`~~

**Comment by lakkiy** [comment]
> 1. what is the version of Firefox?
> 2. have u tried reinstalling Firefox?

1. 
```firefox-developer-edition -v```
```Mozilla Firefox 78.0b2```

2. No, but I config it after I install firefox, didn't move anything else.

Should I try to reinstalling Firefox or switch to Firefox rather than firefox-developer-edition?

**Comment by 3r3bu5x9** [comment]
yes install the regular firefox. the defaults/pref folder is auto-generated.

**Comment by lakkiy** [comment]
> yes install the regular firefox. the defaults/pref folder is auto-generated.

I will try it.  Thanks for your answer 😄️

**Comment by 3r3bu5x9** [comment]
Downloaded and checked firefox-dev-edition from the official website. The defaults/pref folder is already present and everything is working fine. So download it from the [official website](https://www.mozilla.org/en-US/firefox/developer/).

**Comment by lakkiy** [comment]
I install the regular firefox and it's worked.

**Comment by 3r3bu5x9** [comment]
Ok great
