### ISSUE TITLE
Black background in the online editor of Github gist.

### ISSUE THREAD

**Issue by AlanTheKnight** [dbuxy218/Prismatic-Night#5]
Hello, sir!
I had some experience using your theme and I was really surprised when I went to GitHub Gists and tried to use in-built web text editor. It was black, awful and terrible. After I've deleted everything starting from 53rd line in userContent.css it started working as expected. As I understand, these theme and some css variables not improve the look of websites but hurt their functionality. Result of this css misunderstanding is presented in the photo below.
Best wishes,
AlanTheKnight

![omg-look-at-this-shit](https://user-images.githubusercontent.com/51376126/87252448-cac2b180-c47b-11ea-9735-28e396e1076e.png)

**Comment by 3r3bu5x9** [comment]
That part(53rd line to the end) changes the colors of ublock origin and is not part of the theme. I got it from [here](https://www.reddit.com/r/FirefoxCSS/wiki/index/uubo). I shouldn't have put it there in the first place. I'll remove that part. Close the thread if u don't have any more problems.
