### ISSUE TITLE
Weird Borders in New tab page 

### ISSUE THREAD

**Issue by groovitz** [dbuxy218/Prismatic-Night#6]
![2020-09-04-234032_1920x1080_scrot](https://user-images.githubusercontent.com/56974811/92272970-26ec0400-ef08-11ea-9cb7-5c1681c2625e.png)
This is what it looks like. Please help me solve it.

**Comment by 3r3bu5x9** [comment]
Does this happen when ff is in full screen mode or at all times?
Also, does the borders go away when you zoom in/ zoom out?

**Comment by 3r3bu5x9** [comment]
Try this and tell me if the issue is fixed(coz i kind of know what's causing the problem but i can't reproduce it xD):

Open startpage/style.css in a text editor and remove the first line i.e. "html,"

Then save it and refresh the page.

**Comment by groovitz** [comment]
Hey thanks for replying. It does happen in fullscreen mode and when I zoom and zoom out. It doesn't seem to be going.
I'll try removing the first line from style.css and get back to you

**Comment by groovitz** [comment]
![2020-09-05-160104_1920x1080_scrot](https://user-images.githubusercontent.com/56974811/92303296-1b90eb00-ef91-11ea-9823-4e9775106ba0.png)
It's even wierder after removing html

**Comment by 3r3bu5x9** [comment]
yep. i updated the style.css in my repo. use the updated file/code and tell me.

**Comment by groovitz** [comment]
![2020-09-05-160709_1920x1080_scrot](https://user-images.githubusercontent.com/56974811/92303384-e5a03680-ef91-11ea-860f-5fc9850eb37c.png)
Oh boy. I added the new html section. Its gotten even jankier somehow. I think the align content: center is at fault. I dont know much about html, is there a align-cointent: fill or something?

**Comment by 3r3bu5x9** [comment]
go to this link: https://dbuxy218.github.io/Prismatic-Night/

same problem?

**Comment by groovitz** [comment]
No. That page appears properly

**Comment by 3r3bu5x9** [comment]
but it's the same code....

**Comment by 3r3bu5x9** [comment]
what's your firefox version?

**Comment by groovitz** [comment]
80.0 is what it says

**Comment by dbuxy218** [comment]
hamburger menu(3 horizontal lines; top right) > Help > About Firefox

**Comment by groovitz** [comment]
Ya 80.0

**Comment by 3r3bu5x9** [comment]
so the live startpage works but the local one doesn't. So weird xD. Let me look around for solutions. I can't even reproduce the problem...

**Comment by groovitz** [comment]
:((((
Is there a way I can just use the live startpage as the newtab

**Comment by 3r3bu5x9** [comment]
replace the files in startpage folder with the ones here https://github.com/dbuxy218/PixelFox/tree/master/startpage_alt

and tell me whether the weird border is gone or not.

**Comment by 3r3bu5x9** [comment]
you said that you added the "new html section" from the updated style.css in this repo, right? replace the whole thing, all the lines in the file, not just the html section.

**Comment by groovitz** [comment]
Should I also remove scripts directory?

**Comment by groovitz** [comment]
> you said that you added the "new html section" from the updated style.css in this repo, right? replace the whole thing, all the lines in the file, not just the html section.
Im so sorry. I'll try that and see

**Comment by 3r3bu5x9** [comment]
no wait first check my latest comment(before this one)

**Comment by groovitz** [comment]
Bruh. Im a dumbass. It works now. Thanks so much. Btw I love your dots. Keep up the great work man 
![2020-09-05-164557_1920x1080_scrot](https://user-images.githubusercontent.com/56974811/92303942-4aaa5b00-ef97-11ea-8d38-0d4aac4aa292.png)

**Comment by 3r3bu5x9** [comment]
ok no problem man. i'm glad that's fixed! xD
